[CmdletBinding()]
param(
  [switch]$Quiet
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Invoke-Git {
  param([string[]]$GitArgs)

  $previousErrorAction = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  $output = & git @GitArgs 2>&1
  $exitCode = $LASTEXITCODE
  $ErrorActionPreference = $previousErrorAction

  $outputText = ($output | ForEach-Object { "$_" })
  if ($exitCode -ne 0) {
    $cmd = "git $($GitArgs -join ' ')"
    throw "$cmd failed.`n$($outputText -join "`n")"
  }
  return $outputText
}

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
Set-Location $repoRoot

$time = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssK")
$branch = (Invoke-Git @("branch", "--show-current") | Select-Object -First 1).Trim()
$sha = (Invoke-Git @("rev-parse", "--short", "HEAD") | Select-Object -First 1).Trim()
$subject = (Invoke-Git @("log", "-1", "--pretty=%s") | Select-Object -First 1).Trim()
$status = @(Invoke-Git @("status", "--short"))
$dirty = @($status | Where-Object { $_.Trim().Length -gt 0 })

$latestCheckpoint = ""
$latestPath = Join-Path $repoRoot ".checkpoints/latest.json"
if (Test-Path $latestPath) {
  try {
    $cp = (Get-Content -Path $latestPath -Raw | ConvertFrom-Json)
    $latestCheckpoint = "$($cp.checkpoint_id) ($($cp.stage))"
  } catch {
    $latestCheckpoint = "unreadable latest checkpoint metadata"
  }
}
if ([string]::IsNullOrWhiteSpace($latestCheckpoint)) {
  $latestCheckpoint = "not available"
}

$recentCommits = @(Invoke-Git @("log", "--oneline", "-n", "5"))
$recentSync = ""
$syncLog = Join-Path $repoRoot "docs/workflow/agent-sync-log.md"
if (Test-Path $syncLog) {
  $recentSync = (Get-Content -Path $syncLog | Select-Object -Last 5) -join "`n"
}
if ([string]::IsNullOrWhiteSpace($recentSync)) {
  $recentSync = "(no sync entries yet)"
}

$dirtySection = if (@($dirty).Count -gt 0) {
  ($dirty | ForEach-Object { "- $_" }) -join "`n"
} else {
  "- clean worktree"
}

$recentCommitSection = if (@($recentCommits).Count -gt 0) {
  ($recentCommits | ForEach-Object { "- $_" }) -join "`n"
} else {
  "- no commits"
}

$packet = @"
# Compact Packet (Latest)

Generated by scripts/generate-compact-packet.ps1 at $time.

## Keep This Context
- Active branch: $branch
- Latest commit: $sha
- Latest subject: $subject
- Latest checkpoint: $latestCheckpoint

## Uncommitted Changes
$dirtySection

## Recent Commits
$recentCommitSection

## Recent Agent Sync (tail)
~~~text
$recentSync
~~~

## Suggested Compact Prompt
Use this exact line:
/compact Continue from branch $branch at commit $sha. Next action: read docs/development-memory.md and latest checkpoint metadata, then execute next stage task.
"@

$target = Join-Path $repoRoot "docs/workflow/compact-packet-latest.md"
Set-Content -Path $target -Value $packet -Encoding UTF8

if (-not $Quiet) {
  Write-Host "Compact packet written: $target"
}
